### ISSUE TITLE
how to run tests / php8

### ISSUE THREAD

**Issue by tacman** [KnpLabs/KnpMarkdownBundle#108]
I've forked the bundle to allow php8, but can't figure out how to run tests before submitting a PR.

I know this is a dumb question, and it's not specific to this bundle, but even following the Symfony documentation I'm not sure what command to run.  I'll see if I can get this to work with PHP8 if someone can point me in the right direction for tests.

Thanks!

```bash
tac@pop-os:~/survos/KnpMarkdownBundle$ vendor/bin/simple-phpunit 
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Time: 14 ms, Memory: 4.00 MB

No tests executed!


tac@pop-os:~/survos/KnpMarkdownBundle$ vendor/bin/simple-phpunit Tests/
PHP Fatal error:  Uncaught Error: Class "PHPUnit_Framework_TestCase" not found in /home/tac/survos/KnpMarkdownBundle/Tests/EscapingTest.php:7
Stack trace:
#0 /home/tac/survos/KnpMarkdownBundle/vendor/bin/.phpunit/phpunit-7.5-0/src/Util/FileLoader.php(57): include_once()
#1 /home/tac/survos/KnpMarkdownBundle/vendor/bin/.phpunit/phpunit-7.5-0/src/Util/FileLoader.php(45): PHPUnit\Util\FileLoader::load()
#2 /home/tac/survos/KnpMarkdownBundle/vendor/bin/.phpunit/phpunit-7.5-0/src/Framework/TestSuite.php(540): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /home/tac/survos/KnpMarkdownBundle/vendor/bin/.phpunit/phpunit-7.5-0/src/Framework/TestSuite.php(618): PHPUnit\Framework\TestSuite->addTestFile()
#4 /home/tac/survos/KnpMarkdownBundle/vendor/bin/.phpunit/phpunit-7.5-0/src/Runner/BaseTestRunner.php(97): PHPUnit\Framework\TestSuite->addTestFiles()
#5 /home/tac/survos/KnpMarkdownBundle/vendor/bin/.phpunit/phpunit-7.5-0/src/TextUI/Command.php(183): PHPUnit\Runner\BaseTestRunner->getTest()
#6 /home/tac/survos/KnpMarkdownBundle/vendor/bin/.phpunit/phpunit-7.5-0/src/TextUI/Command.php(162): PHPUnit\TextUI\Command->run()
#7 /home/tac/survos/KnpMarkdownBundle/vendor/bin/.phpunit/phpunit-7.5-0/phpunit(22): PHPUnit\TextUI\Command::main()
#8 /home/tac/survos/KnpMarkdownBundle/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(415): include('...')
#9 /home/tac/survos/KnpMarkdownBundle/vendor/symfony/phpunit-bridge/bin/simple-phpunit(13): require('...')
#10 {main}
  thrown in /home/tac/survos/KnpMarkdownBundle/Tests/EscapingTest.php on line 7
tac@pop-os:~/survos/KnpMarkdownBundle$ 
```

**Comment by tacman** [comment]
I've create a PR for allowing Symfony 6, but I'm still not sure how to run tests.  @weaverryan or anyone, can you point me in the right direction?  Thx.

**Comment by Chris53897** [comment]
@tacman You can run `./vendor/bin/phpunit` Details to [phpunit](https://phpunit.de/getting-started/phpunit-9.html) or use this file and activate github actions on your fork. (good to test multiple php versions / options / environments)
https://github.com/KnpLabs/KnpMarkdownBundle/blob/e236495e4c200fb2bdf4c78b748c62edf80231f4/.github/workflows/code_checks.yml
